version: '3.6'

services:
  cache:
    build: ./.docker/redis
    restart: always
    ports:
      - 6379:6379
  db:
    build: ./.docker/postgres
    restart: always
    environment: 
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - ./.docker/dbdata:/var/lib/postgresql/data

  api:
    build: .
    depends_on:
      - cache
      - db
    entrypoint: sh -c "yarn && yarn start:dev"
    ports:
      - 8080:8080
    volumes:
      - .:/home/node/api